apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sigms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: secrets-account
      containers:
        - image: europe-west1-docker.pkg.dev/rising-city-464516-e8/sigms/backend
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: sigms-secret-provider
          env:
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: EMAIL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: JWT_SECRET
            - name: MICROSOFT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: MICROSOFT_CLIENT_ID
            - name: MICROSOFT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: MICROSOFT_CLIENT_SECRET
            - name: MICROSOFT_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: MICROSOFT_TENANT_ID
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sigms-secret-provider
                  key: DB_USER