ktor:
  application:
    modules:
      - isel.leic.group25.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: "sigms"
  issuer: "http://localhost:8080/"
  audience: "http://localhost:8080/"
  realm: "Access to 'isel.leic.group25'"

