ktor:
  application:
    modules:
      - isel.leic.group25.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: "sigms"
  issuer: "http://localhost:8080/"
  audience: "http://localhost:8080/"
  realm: "Access to 'isel.leic.group25'"
frontend:
  url: "http://localhost:8080/"
email:
  host: "smtp.yourdomain.com"
  port: 587
  username: "noreply@yourdomain.com"
  password: "your-email-password"
  from: "noreply@yourdomain.com"
  useSsl: true
