@baseUrl = http://localhost:8080/api

###
GET {{baseUrl}}

<> 2025-04-03T145716.200.json
<> 2025-04-02T214354.200.json
<> 2025-04-02T164315.200.json

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonio227@gmail.com",
  "username": "Antonio_123",
  "password": "Antonio_123",
  "role": "teacher"
}


<> 2025-04-05T142635.201.json

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin1@example.com",
  "password": "Antonio_123"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyIsInVzZXJJZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzQ1NDI0MzQxLCJleHAiOjE3NDU0Mjc5NDF9.PZ9kIqqHMczyOf0zoEzGB38KdO_BJvCY9Nr0nTnexT0


###
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}


###
PUT {{baseUrl}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "Antonio_124",
    "image": []
}

###
POST {{baseUrl}}/profile/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "oldPassword": "Antonio_123",
    "newPassword": "Antonio_567"
}

###
GET {{baseUrl}}/subjects
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/subjects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "CDI"
}

###
GET {{baseUrl}}/subjects/1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/subjects/1/classes
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/subjects/2/classes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "LEIC51D"
}

###
POST {{baseUrl}}/subjects/1/classes/1/users
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE {{baseUrl}}/subjects/1/classes/1/users
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET {{baseUrl}}/subjects/1/classes/1/lectures
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms/1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "G.2.03",
  "capacity": 30,
  "type": "class"
}

###
GET {{baseUrl}}/rooms/1/lectures
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms/1/issues
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/rooms/1/issues
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "The projector is not working"
}

###
GET {{baseUrl}}/rooms/1/issues/1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/lectures
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/lectures
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "schoolClassId": 3,
  "roomId": 2,
  "startTime": "17:30",
  "endTime": "18:00",
  "type": "THEORETICAL",
  "weekDay": "TUESDAY"
}

###
GET {{baseUrl}}/schedule
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET {{baseUrl}}/assesRole
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/assesRole/20ef8acc-072e-421d-a039-a2a860b3d602
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/assesRole?token=20ef8acc-072e-421d-a039-a2a860b3d602&status=approved
Authorization: Bearer {{token}}