@baseUrl = http://localhost:8080/api

###
GET {{baseUrl}}

<> 2025-04-03T145716.200.json
<> 2025-04-02T214354.200.json
<> 2025-04-02T164315.200.json

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonio229@gmail.com",
  "username": "Antonio_123",
  "password": "Antonio_123",
  "role": "student"
}


<> 2025-04-05T142635.201.json

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "antonio229@gmail.com",
  "password": "Antonio_123"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyIsInVzZXJJZCI6MSwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NDQ5MDA0MzUsImV4cCI6MTc0NDkwNDAzNX0.aw1JUMfzVFJs6Sx-7ixRGe427ERJF0GgsaiDKemCwnk


###
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}


###
PUT {{baseUrl}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "Antonio_124",
    "image": []
}

###
POST {{baseUrl}}/profile/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "oldPassword": "Antonio_123",
    "newPassword": "Antonio_567"
}

###
GET {{baseUrl}}/subjects
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/subjects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Mathematics"
}

###
GET {{baseUrl}}/subjects/1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/subjects/1/classes
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/subjects/1/classes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "LEIC51D"
}

###
GET {{baseUrl}}/subjects/1/classes/1/lectures
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms/1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "G.2.02",
  "capacity": 30,
  "type": "class"
}

###
GET {{baseUrl}}/rooms/1/lectures
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms/1/issues
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/rooms/1/issues
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "The projector is not working again"
}

###
GET {{baseUrl}}/rooms/1/issues/1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/lectures
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/lectures
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "schoolClassId": 1,
  "roomId": 1,
  "startTime": "18:30",
  "endTime": "19:00",
  "type": "THEORETICAL",
  "weekDay": "MONDAY"
}




