services:
  db:
    build:
      context: ../backend
      dockerfile: ./db/Dockerfile
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sigms
    ports:
      - "5432:5432"
    volumes:
      - ../backend/db:/docker-entrypoint-initdb.d
    networks:
      - sigms-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d sigms" ]
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ../backend
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../backend/docker/.env
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sigms-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - sigms-network
    depends_on:
      - backend

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port (for sending emails)
      - "8025:8025"  # Web UI port (to view emails)
    networks:
      - sigms-network

networks:
  sigms-network:
    driver: bridge