services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sigms
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint-initdb.d
    networks:
      - sigms-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sigms-network

networks:
  sigms-network:
    driver: bridge