
###
GET {{baseUrl}}/rooms
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms/asfgsfagd
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/rooms/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "F.2.03",
  "capacity": 30,
  "type": "study"
}

###
GET {{baseUrl}}/rooms/3/lectures
Authorization: Bearer {{token}}