apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sigms
  annotations:
    cloud.google.com/load-balancer-type: "External"
    networking.gke.io/load-balancer-name: "sigms-net-lb"
spec:
  selector:
    app: frontend
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer