
###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioStudent2@gmail.com",
  "username": "Antonio_123",
  "password": "Antonio_123",
  "role": "student"
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin2@example.com",
  "password": "Antonio_123"
}

###
PUT {{baseUrl}}/auth/verifyAccount?token=fb0d707d-2e0c-432d-ab66-b379c8ff207e

###
GET {{baseUrl}}/assessRole
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/assessRole/684a7f17-62f0-45a8-87b8-ce44c8f131fe
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/assessRole?token=684a7f17-62f0-45a8-87b8-ce44c8f131fe&status=approved
Authorization: Bearer {{token}}

