
###
# for student ()
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioStudent15@gmail.com",
  "username": "Antonio_124",
  "password": "Antonio_124",
  "universityId": 1,
  "role": "student"
}

###
# for teacher ()
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioTeacher16@gmail.com",
  "username": "Antonio_124",
  "password": "Antonio_124",
  "universityId": 1,
  "role": "teacher"
}

###
# for technical service ()
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioTS15@gmail.com",
  "username": "Antonio_124",
  "password": "Antonio_124",
  "role": "technical_services"
}

###
# @name login
#
POST {{baseUrl}}/auth/login
Content-Type: application/json
X-Device: WEB

{
  "email": "antonioStudent15@gmail.com",
  "password": "Antonio_124"
}


###
#
PUT {{baseUrl}}/auth/verify-account?token=0e07a389-2f59-4dbf-9c46-65d456aa1ea6

###
GET {{baseUrl}}/assess-roles
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/assess-roles/ec3e412a-98b5-4bed-a4aa-a9d14060cb85
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/assess-roles/validate?token=ec3e412a-98b5-4bed-a4aa-a9d14060cb85&status=approved
Authorization: Bearer {{token}}

