
###
# for student ()
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioStudent15@gmail.com",
  "username": "Antonio_124",
  "password": "Antonio_124",
  "role": "student"
}

###
# for teacher ()
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioTeacher16@gmail.com",
  "username": "Antonio_124",
  "password": "Antonio_124",
  "role": "teacher"
}

###
# for technical service ()
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "antonioTS15@gmail.com",
  "username": "Antonio_124",
  "password": "Antonio_124",
  "role": "technical_services"
}

###
# @name login
#
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin1@example.com",
  "password": "Antonio_124"
}


###
#
PUT {{baseUrl}}/auth/verify-account?token=6d2e73cd-d7f6-4b23-95e2-9e37f2649e11

###
GET {{baseUrl}}/assess-roles
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/assess-roles/ec3e412a-98b5-4bed-a4aa-a9d14060cb85
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/assess-roles/validate?token=ec3e412a-98b5-4bed-a4aa-a9d14060cb85&status=approved
Authorization: Bearer {{token}}

