
###
GET {{baseUrl}}/rooms
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/rooms/1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "F.2.05",
  "capacity": 30,
  "type": "class"
}

###
GET {{baseUrl}}/rooms/3/lectures
Authorization: Bearer {{token}}