
###
GET {{baseUrl}}/subjects
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/subjects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "PG"
}

###
GET {{baseUrl}}/subjects/1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/subjects/1/classes
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/subjects/1/classes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "LEIC51D"
}

###
GET {{baseUrl}}/subjects/1/classes/3/lectures
Authorization: Bearer {{token}}